
// ********************** Problem 4 **********************


// ********************** Problem 3 **********************
// The prime factors of 13195 are 5, 7, 13 and 29.
// What is the largest prime factor of the number 600851475143 ?
var num = 600851475143, factors = [], solution = 1, j = 0;
for (var i = 2; solution < num; i++) {
  if (num % i == 0) {
  	factors.push(i);
		solution *= factors[j];
		// console.log("solution total so far = " + solution);
		// console.log("new factor = " + factors[j]);
		// console.log("current array index j = " + j);
		j++;
  }
}
console.log(factors);
// <- [71, 839, 1471, 6857] (answer is 6857)


// ********************** Problem 2 **********************
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
var i = 1, j = 2, sum = 2;
for (var k = 0; k < 4000001;) {
	k = (j + i);
	if (k % 2 == 0) {
		sum += k;
	}
	i = j;
	j = k;
}
console.log(sum);
// <- 4613732 (answer)


// ********************** Problem 1 **********************
// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
// Find the sum of all the multiples of 3 or 5 below 1000.
var sum = 0;
for (var i = 1; i < 1000; i++) {
	if (i % 3 == 0 || i % 5 == 0) {
		sum += i;
	}
}
console.log(sum);
// <- 233168 (answer)
